server:
  addr: ":8090"
  read_timeout: 10s
  write_timeout: 30s

database:
  url:  "postgresql://postgres:password@localhost:5433/devboard?sslmode=disable"
  max_conns:  25 # numero de nucleos * 2 o 4
  min_conns:  5
  max_conn_livetime:  1h
  max_conn_idle_time: 30m

app:
  env:  "development"