basePath: /api/v1
definitions:
  handler.healthResponse:
    properties:
      status:
        type: string
      version:
        type: string
    type: object
host: localhost:8090
info:
  contact: {}
  description: API REST para la gestión de proyectos
  title: Devboard API
  version: "1.0"
paths:
  /health:
    get:
      description: Verifica que el servidor está corriendo y respondiendo
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.healthResponse'
      summary: Health check
      tags:
      - system
swagger: "2.0"
